version: '3.9'
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: buy-and-sell_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - buy-and-sell_data:/data/db

  db_ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: buy-and-sell_mongo_express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/

volumes:
  buy-and-sell_data:
